# Generated by Django 3.1.1 on 2020-09-10 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='admin',
        ),
        migrations.AlterField(
            model_name='message',
            name='admin_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='client',
            field=models.CharField(default='Anonymous', max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='client_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
